# pytorch_lightning==2.1.0
seed_everything: 123
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: 1000
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: 4
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 20
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  model: 
    class_path: beat_tracker.models.TCN.BeatTrackingTCN
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.001
      weight_decay: 0
  scheduler:
  # reduce_on_plateau
    class_path: torch.optim.lr_scheduler.ReduceLROnPlateau
    init_args:
      mode: min
      factor: 0.2
      patience: 50
      threshold: 0.0001
      threshold_mode: rel
      cooldown: 0
      min_lr: 0
      monitor: val_loss

  beat_vs_downbeat_loss_ratio: 1
data:
  tasks:
  - ballroom_mel
  target_sr: 44100
  target_seconds: 30
  n_fft: 2048
  fps: 100
  n_mels: 81
  batch_size: 1
  val_split: 0.1
  test_split: 0.1
  num_workers: 8
  kfolds: null
  transform: false
log: false
ckpt_path: checkpoints
resume_id: null
resume_from_checkpoint: null
test: false
early_stopping_patience: 100
